unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

set -g mouse on
set -g set-clipboard on

bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Copy to Linux system clipboard on mouse release
bind-key -T copy-mode MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -i"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -i"
